spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
server:
  port: 8081

